# -*- coding: utf-8 -*-
"""axisnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10t7OEn-UQpZ0x-WJKllQnNiOHTPD4pFZ
"""

!pip install google-play-scraper

from google_play_scraper import app
import pandas as pd
import numpy as np
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.axis.net',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=100,
    filter_score_with=None
)
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False)
sorted_df.to_csv("ulasanaxis.csv", index = False)